name: CI workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim  # Running in a Python container

    steps:
      - name: Checkout
        uses: actions/checkout@v3
